package amcode.application.common.enums;

public enum View {
    LOGIN_VIEW,
    MAIN_VIEW,
    PROFILE_VIEW,
    EXERCISE_HISTORY_VIEW,
    NEW_ALERT_VIEW,
    MODIFY_ALERT_VIEW,
    ALERT_LIST_VIEW,
    NEW_ACCOUNT_VIEW,
    NOTIFICATION_VIEW,
    ON_EXERCISE_VIEW,
    START_VIEW,
    TRIGGER_ALERT_VIEW
}
